### ISSUE TITLE
Pause in the synthesis of "Consapevole"

### ISSUE THREAD

**Issue by smithme** [watson-developer-cloud/text-to-speech-nodejs#44] opened 2016-01-28 19:18 UTC
There is a pause in the middle of the first word "Consapevole" when synthesizing the default Italian text.
This problem seems to only happen when using Firefox. Works ok on Chrome.
Downloading the audio works fine. I only see this problem when the audio is streamed.

**Comment by germanattanasio** [comment] 2016-01-28 19:29
This looks like one of those weird issues related to how the browser plays the audio file...

**Comment by germanattanasio** [comment] 2016-01-28 19:30
since it's the first word and it's in firefox it could be the browser that realize that the file size is not part of the header...

**Comment by germanattanasio** [comment] 2016-01-28 19:30
@daniel-bolanos what do you think?

**Comment by daniel-bolanos** [comment] 2016-01-28 23:46
@smithme  I cannot reproduce this issue in Firefox, my version is 43.0.4, the audio for that word is played back perfectly.
@germanattanasio can you reproduce it yourself?

**Comment by smithme** [comment] 2016-01-29 13:32
I am running Firefox on a Windows 7 system.  I have Firefox ESR, version is 38.5.2.

**Comment by germanattanasio** [comment] 2016-03-30 04:01
I can't reproduce the problem in Firefox on a windows 7 so I'm closing the issue. Probably a network hiccup

**Closed by germanattanasio** 2016-03-30 04:01 UTC
Labels: bug
