### ISSUE TITLE
Synthesize stops when text contains invalid character(s)

### ISSUE THREAD

**Issue by Atreilly** [watson-developer-cloud/text-to-speech-nodejs#60] opened 2016-06-29 02:32 UTC
TTS DEMO -- For all  in US English Voices only, after pressing "Speak" button the program begins to synthesize text to speech, but stops before the end when text contains invalid character

Expected: For all voices, program synthesizes all text, with any character, to speech
Actual: For US English voices, program does not synthesize text, with invalid character, to speech

Note: 
As per Radek, "This is a bug in the demopage; it works fine when communicating directly with  https://stream-d.watsonplatform.net/text-to-speech/api/v1/synthesize?voice=en-US_AllisonVoice"

See details below:
When en-US_AllisonVoice, en-US_LisaVoice, or en-US_MichaelVoice is selected, and the text below is entered, and you press "Speak" the program stops speaking at the point "Stops speaking here" is stated in the text box.
And an audio file is successfully created containing only the part spoken out loud and not the entire text.
When any other voice is selected, the program works correctly and completes successfully by not stopping in the middle of the text.

Example text in text box:
 Italian:
`<phoneme alphabet="ipa" ph=".ʤe.ˈla.to"></phoneme>
 <phoneme alphabet="ibm" ph="1byan.0ko"></phoneme>`

English:
`<phoneme alphabet="ipa" ph="təˈmeɪ.ɾoʊ"></phoneme> 
<phoneme alphabet="ipa" ph="təˈmeɪ.ɾoʊ"></phoneme> 
<phoneme alphabet="ibm" ph=".0tx.1me.0Fo"></phoneme>`

Castillian Spanish:
`<phoneme alphabet="ipa" ph=".ˈθiŋ.ko"></phoneme>
 <phoneme alphabet="ibm" ph="1Tin.0ko"></phoneme>`

Italian:
`<phoneme alphabet="ipa" ph=".ʤe.ˈla.to"></phoneme>
 <phoneme alphabet="ibm" ph="1byan.0ko"></phoneme>`

English:
`<phoneme alphabet="ipa" ph="təˈmeɪ.ɾoʊ"></phoneme> 
<phoneme alphabet="ipa" ph="təˈmeɪ.ɾoʊ"></phoneme>
<phoneme alphabet="ibm" ph=".0tx.1me.0Fo"></phoneme>`

Castillian Spanish:
`<phoneme alphabet="ipa" ph=".ˈθiŋ.ko"></phoneme>
 <phoneme alphabet="ibm" ph="1Tin.0ko"></phoneme>`     -- Stops speaking here

North American Spanish:
`<phoneme alphabet="ipa" ph=".in.di.ˈβi.ðwo"></phoneme>
 <phoneme alphabet="ibm" ph=".0e.1DaD"></phoneme>`

Brazilian Portuguese

<phoneme alphabet="ipa" ph=".ĩ.ˈsẽ.su"></phoneme>
 <phoneme alphabet="ibm" ph=".0o.0bri.1ga.0du"></phoneme>

French:
<phoneme alphabet="ipa" ph=".ʃə.val"></phoneme>
 <phoneme alphabet="ibm" ph="0o.k1'oe~'"></phoneme>

US English
<phoneme alphabet="ipa" ph=".ˈfæst"></phoneme>
 <phoneme alphabet="ibm" ph=".1mH.0DR"></phoneme>

<phoneme alphabet="ipa" ph="təˈmeɪ.ɾoʊ"></phoneme>
 <phoneme alphabet="ibm" ph=".0tx.1me.0Fo"></phoneme>

UK English

<phoneme alphabet="ipa" ph=".ˈbʌ.tən"></phoneme>
 <phoneme alphabet="ibm" ph=".0In.1hEx.0rIt"></phoneme>

German:
<phoneme alphabet="ipa" ph=".ˈʦaʊ.bɐ"></phoneme>
 <phoneme alphabet="ibm" ph=".1h'oj'.0t@"></phoneme>

Alexandra

**Comment by nfriedly** [comment] 2016-06-29 15:32
This seems like a service bug, although we may be able to work around it in the demo. @daniel-bolanos what do you think?

**Comment by kognate** [comment] 2016-10-27 18:59
This is fixed in #71 and should be deployed soon.  The problem is that the error message in the demo was getting suppressed.  The service does return a correct 'Illegal character' error.

**Comment by germanattanasio** [comment] 2016-10-27 22:54
Should we remove the characters that are illegal so that the demo synthesize the text? I down side is that users will expect the API to synthesize the same text

**Comment by kognate** [comment] 2016-10-28 13:39
I've been considering this.  The problem with removing the offending characters is that we don't know how important that character might be.  I think the best thing to do is just pass the service error message to the user so they can understand what happened.  I'm looking into how much more info we can get from the service (like error position, etc).  but synthesis is halted on the error and the service itself doesn't continue.

**Closed** 2016-11-22 17:39 UTC
Labels: bug
